### PR TITLE
Closes #40 Update CDN cname

### LINKED ISSUE #40: RocketCDN CNAME change
**Is your feature request related to a problem? Please describe.**
In the upcoming version we'll need to change the RocketCDN CNAMEs automatically

**Describe the solution you'd like**
The Acceptance Criteria is described here:
https://www.notion.so/wpmedia/RocketCDN-CNAME-change-d72cd2baa88b49b7b4cb65b348440564?pvs=4

### PR DESCRIPTION
**Pull request by remyperona**
# Description

Fixes #40 

Automatically updates the current CDN cname on update of the plugin and display an info notice to inform the user

## Type of change

- [x] Enhancement (non-breaking change which improves an existing functionality).

## Detailed scenario

Update the plugin

### Documentation

*Explain how this code works. Diagrams & drawings are welcome.*

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

### CODE REVIEW

**Review by Khadreal — APPROVED** [review]

**Comment by hanna-meda** [comment]
Thank you, @remyperona, for this PR.
At first glance at it, we see the notification showing also for fresh plugin installations. According to the [specs](https://www.notion.so/wpmedia/RocketCDN-CNAME-change-d72cd2baa88b49b7b4cb65b348440564?pvs=4#6f4d598d6dfb41b2975e8d10e237e03f), we should have the notification only on update from a lower version than 1.0.6.

**Comment by remyperona** [comment]
Updated the code to take care of fresh install and prevent the notice from displaying.

**Comment by hanna-meda** [comment]
@remyperona, retested on [this site](http://mega.wp-rocket.me/divi) where we have rocketcdn staging linked to it, so we can actually see the CNAME updated. There are a few points that still need to be addressed:
1. The Notification will still be present on fresh installs but not immediately. 
It appears after validating API key.
2. The Notification cannot be dismissed. 
Clicking on "X" button doesn't trigger any action.
3. The old name is missing from the notification:
Screenshot 2024-11-11 at 10 36 53

@wp-media/product, I have a question regarding the following scenario:
1. RocketCDN version <=1.0.6 installed & activated, but the API key hasn’t been validated.
2. The user updates to version 1.0.7 => In this case, should we expect the notification to appear? Since the user hasn’t provided their API key yet, we wouldn’t know it.

**Comment by piotrbak** [comment]
@hanna-meda 
```
1. RocketCDN version <=1.0.6 installed & activated, but the API key hasn’t been validated.
2. The user updates to version 1.0.7 => In this case, should we expect the notification to appear? Since the user hasn’t provided their API key yet, we wouldn’t know it.
```
That's kind of edgy. What's the current state?

**Comment by hanna-meda** [comment]
> That's kind of edgy. What's the current state?

@piotrbak the notification will be there.

**Comment by piotrbak** [comment]
@hanna-meda Do you have a screenshot of notification from this scenario? Since the API is not there, we'll not display the URLs?

**Comment by piotrbak** [comment]
@hanna-meda That sounds good if the issue 3 is fixed.

**Comment by remyperona** [comment]
All reported issues should be fixed now

**Comment by hanna-meda** [comment]
Thank you, @remyperona. 
I can confirm all issues are fixed except point 3. The old name is missing from the notification
- Testing on [mega](http://mega.wp-rocket.me/divi/) (site linked to staging rocketCDN website where the  name`delivery` update is in place), the notification banner cannot be triggered anymore:
link to [video](https://github.com/user-attachments/assets/c542fa0c-948a-4fe4-8ea1-fb35ff5e477c)
- Testing on [newer](https://newer.rocketlabsqa.ovh/) (site linked to rocketCDN production), I can see the notification but with old name missing:
Screenshot 2024-11-13 at 14 53 35

**Comment by remyperona** [comment]
Ok I finally found the issue for this point, it should be good now! I tested on the newer site, and got the notification with both old and new CDN URL filled (since it's using production API, it ends up being the same value for now).

**Review by hanna-meda — APPROVED** [review]
Related Test Results Report:
[testrail-report-660.pdf](https://github.com/user-attachments/files/17758621/testrail-report-660.pdf)

**Pull request merged**
